import { useState, useEffect } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import type { Student, TuitionPayment, Team } from "@shared/schema";
import { RefreshCw, Settings, ChevronDown, Download } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { getFullName } from "@/lib/nameUtils";

export default function TuitionPage() {
  // Set page title
  useEffect(() => {
    document.title = "会費管理 | TEAMOコーチ";
  }, []);

  const { toast } = useToast();
  const currentYear = new Date().getFullYear();
  const currentMonth = new Date().getMonth() + 1;
  
  const [selectedYear, setSelectedYear] = useState(currentYear);
  const [selectedMonth, setSelectedMonth] = useState(currentMonth);
  const [editingValues, setEditingValues] = useState<Record<string, {
    baseAmount?: number;
    discount?: number;
    annualFee?: number;
    entranceFee?: number;
    insuranceFee?: number;
    spotFee?: number;
    amount?: number;
  }>>({});
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false);

  const coachData = localStorage.getItem("coachData");
  const teamId = coachData ? JSON.parse(coachData).teamId : null;

  const { data: teams = [] } = useQuery<Team[]>({
    queryKey: ["/api/teams"],
    enabled: !!teamId,
  });

  const team = teams.find(t => t.id === teamId);

  const { data: students = [] } = useQuery<Student[]>({
    queryKey: ["/api/students", team?.id],
    queryFn: async () => {
      if (!team?.id) return [];
      const res = await fetch(`/api/students?teamId=${team.id}`, {
        credentials: "include",
      });
      if (!res.ok) throw new Error("Failed to fetch students");
      return res.json();
    },
    enabled: !!team?.id,
  });

  const { data: payments = [], isLoading } = useQuery<TuitionPayment[]>({
    queryKey: ["/api/tuition-payments", team?.id, selectedYear, selectedMonth],
    queryFn: async () => {
      if (!team?.id) return [];
      const res = await fetch(`/api/tuition-payments?teamId=${team.id}&year=${selectedYear}&month=${selectedMonth}`, {
        credentials: "include",
      });
      if (!res.ok) throw new Error("Failed to fetch tuition payments");
      return res.json();
    },
    enabled: !!team?.id,
  });

  // Fetch sibling status for all students in the team
  const { data: siblingInfoMap = {} } = useQuery<Record<string, { hasSibling: boolean, siblings: Array<{ id: string, lastName: string, firstName: string }> }>>({
    queryKey: [`/api/sibling-links/team/${team?.id}/status`],
    enabled: !!team?.id,
  });

  const handleExportCSV = async () => {
    if (!team) return;
    
    try {
      const response = await fetch(
        `/api/tuition-payments/export?teamId=${team.id}&year=${selectedYear}&month=${selectedMonth}`,
        { credentials: "include" }
      );
      
      if (!response.ok) throw new Error("CSVのダウンロードに失敗しました");
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `tuition_${selectedYear}_${selectedMonth}_${new Date().toISOString().split('T')[0]}.csv`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      
      toast({
        title: "ダウンロード成功",
        description: "月謝データをCSVでダウンロードしました",
      });
    } catch (error) {
      console.error("Export error:", error);
      toast({
        title: "エラー",
        description: "CSVのダウンロードに失敗しました",
        variant: "destructive",
      });
    }
  };

  const autoGenerateMutation = useMutation({
    mutationFn: async () => {
      if (!team) throw new Error("チームが見つかりません");
      const response = await apiRequest("POST", "/api/tuition-payments/reset-unpaid", {
        teamId: team.id,
        year: selectedYear,
        month: selectedMonth,
      });
      return await response.json();
    },
    onSuccess: (data: any) => {
      queryClient.invalidateQueries({ 
        queryKey: ["/api/tuition-payments"] 
      });
      queryClient.invalidateQueries({
        queryKey: ["/api/students"]
      });
      
      const count = data.resetCount || 0;
      toast({
        title: "初期化成功",
        description: `${count}件の未入金データを初期化しました`,
      });
    },
    onError: (error: any) => {
      console.error("Reset error:", error);
      toast({
        title: "エラー",
        description: error.message || "月謝データの初期化に失敗しました",
        variant: "destructive",
      });
    },
  });

  const updatePaymentMutation = useMutation({
    mutationFn: async (data: { 
      studentId: string; 
      baseAmount?: number;
      discount?: number;
      annualFee?: number;
      entranceFee?: number;
      insuranceFee?: number;
      spotFee?: number;
      amount?: number; 
      isPaid?: boolean; 
      category?: string | null 
    }) => {
      return await apiRequest("POST", "/api/tuition-payments", {
        ...data,
        year: selectedYear,
        month: selectedMonth,
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ 
        queryKey: ["/api/tuition-payments"] 
      });
      toast({
        title: "更新成功",
        description: "月謝情報を更新しました",
      });
    },
  });

  // Get sibling discount status based on actual sibling links
  const getSiblingDiscountStatus = (studentId: string) => {
    const siblingInfo = siblingInfoMap[studentId];
    if (siblingInfo && siblingInfo.hasSibling && siblingInfo.siblings.length > 0) {
      // Display first sibling name (if there are multiple siblings, show the first one)
      const sibling = siblingInfo.siblings[0];
      return `兄弟 ${getFullName(sibling.lastName, sibling.firstName)}`;
    }
    return " ";
  };

  const getPaymentForStudent = (studentId: string) => {
    return payments.find((p) => p.studentId === studentId);
  };

  const getDefaultBaseAmount = (student: Student) => {
    if (!team) return 0;
    if (student.playerType === "team") {
      return team.monthlyFeeMember || 0;
    } else if (student.playerType === "school") {
      return team.monthlyFeeSchool || 0;
    }
    // 休部や未設定の場合は0
    return 0;
  };

  const getDefaultAnnualFee = () => {
    if (!team) return 0;
    // 年会費課金月には年会費を自動設定
    if (selectedMonth === (team.annualFeeMonth || 4)) {
      return team.annualFee || 0;
    }
    return 0;
  };

  const getDefaultEntranceFee = () => {
    // 入会金は自動設定しない（手動で設定）
    return 0;
  };

  const getDefaultInsuranceFee = () => {
    if (!team) return 0;
    // 保険料課金月には保険料を自動設定
    if (selectedMonth === (team.insuranceFeeMonth || 4)) {
      return team.insuranceFee || 0;
    }
    return 0;
  };

  const getEditingValue = (studentId: string, field: keyof typeof editingValues[string], defaultValue: number) => {
    return editingValues[studentId]?.[field] ?? defaultValue;
  };

  const setEditingValue = (studentId: string, field: keyof typeof editingValues[string], value: number) => {
    setEditingValues(prev => ({
      ...prev,
      [studentId]: {
        ...prev[studentId],
        [field]: value,
      }
    }));
  };

  const calculateTotal = (studentId: string) => {
    const payment = getPaymentForStudent(studentId);
    const student = students.find(s => s.id === studentId);
    
    const baseAmount = getEditingValue(
      studentId, 
      'baseAmount', 
      payment?.baseAmount ?? getDefaultBaseAmount(student!)
    );
    const discount = getEditingValue(studentId, 'discount', payment?.discount ?? 0);
    const annualFee = getEditingValue(
      studentId, 
      'annualFee', 
      payment?.annualFee ?? getDefaultAnnualFee()
    );
    const entranceFee = getEditingValue(
      studentId, 
      'entranceFee', 
      payment?.entranceFee ?? getDefaultEntranceFee()
    );
    const insuranceFee = getEditingValue(
      studentId, 
      'insuranceFee', 
      payment?.insuranceFee ?? getDefaultInsuranceFee()
    );
    const spotFee = getEditingValue(studentId, 'spotFee', payment?.spotFee ?? 0);
    
    return baseAmount - discount + annualFee + entranceFee + insuranceFee + spotFee;
  };

  const handleFieldUpdate = (studentId: string, field: 'baseAmount' | 'discount' | 'annualFee' | 'entranceFee' | 'insuranceFee' | 'spotFee' | 'amount') => {
    const payment = getPaymentForStudent(studentId);
    const student = students.find(s => s.id === studentId);
    const value = editingValues[studentId]?.[field];
    
    if (value === undefined) return;

    // 他のフィールドの現在の値を取得
    const baseAmount = field === 'baseAmount' ? value : (payment?.baseAmount ?? getDefaultBaseAmount(student!));
    const discount = field === 'discount' ? value : (payment?.discount ?? 0);
    const annualFee = field === 'annualFee' ? value : (payment?.annualFee ?? getDefaultAnnualFee());
    const entranceFee = field === 'entranceFee' ? value : (payment?.entranceFee ?? getDefaultEntranceFee());
    const insuranceFee = field === 'insuranceFee' ? value : (payment?.insuranceFee ?? getDefaultInsuranceFee());
    const spotFee = field === 'spotFee' ? value : (payment?.spotFee ?? 0);
    
    // 合計金額を計算（手動編集の場合は編集値を使用）
    const amount = field === 'amount' ? value : (baseAmount - discount + annualFee + entranceFee + insuranceFee + spotFee);

    updatePaymentMutation.mutate({
      studentId,
      baseAmount,
      discount,
      annualFee,
      entranceFee,
      insuranceFee,
      spotFee,
      amount,
      isPaid: payment?.isPaid || false,
      category: payment?.category || (student?.playerType === "team" ? "team" : student?.playerType === "school" ? "school" : null),
    });

    // 編集値をクリア
    setEditingValues(prev => {
      const newValues = { ...prev };
      delete newValues[studentId];
      return newValues;
    });
  };

  const handlePaidToggle = (studentId: string, isPaid: boolean) => {
    const payment = getPaymentForStudent(studentId);
    const student = students.find((s) => s.id === studentId);
    
    updatePaymentMutation.mutate({
      studentId,
      baseAmount: payment?.baseAmount ?? getDefaultBaseAmount(student!),
      discount: payment?.discount ?? 0,
      annualFee: payment?.annualFee ?? getDefaultAnnualFee(),
      entranceFee: payment?.entranceFee ?? getDefaultEntranceFee(),
      insuranceFee: payment?.insuranceFee ?? getDefaultInsuranceFee(),
      spotFee: payment?.spotFee ?? 0,
      amount: payment?.amount ?? calculateTotal(studentId),
      isPaid,
      category: payment?.category || (student?.playerType === "team" ? "team" : student?.playerType === "school" ? "school" : null),
    });
  };

  const updateStudentPlayerTypeMutation = useMutation({
    mutationFn: async (data: { studentId: string; playerType: string | null }) => {
      return await apiRequest("PATCH", `/api/student/${data.studentId}`, {
        playerType: data.playerType,
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: ["/api/students"]
      });
    },
  });

  const handleCategoryChange = async (studentId: string, playerType: string | null) => {
    const payment = getPaymentForStudent(studentId);
    const student = students.find((s) => s.id === studentId);
    
    // playerTypeをそのまま使用（team, school, inactive, null）
    // categoryは月謝計算用に変換（休部の場合はnull扱い）
    const category = playerType === "inactive" ? null : playerType;
    
    // まず月謝データを更新
    updatePaymentMutation.mutate({
      studentId,
      baseAmount: payment?.baseAmount ?? getDefaultBaseAmount(student!),
      discount: payment?.discount ?? 0,
      annualFee: payment?.annualFee ?? getDefaultAnnualFee(),
      entranceFee: payment?.entranceFee ?? getDefaultEntranceFee(),
      insuranceFee: payment?.insuranceFee ?? getDefaultInsuranceFee(),
      spotFee: payment?.spotFee ?? 0,
      amount: payment?.amount ?? calculateTotal(studentId),
      isPaid: payment?.isPaid || false,
      category,
    });

    // 次にstudentのplayerTypeも更新（区分を保存）
    updateStudentPlayerTypeMutation.mutate({
      studentId,
      playerType: playerType || "",
    });
  };

  const years = Array.from({ length: 5 }, (_, i) => currentYear - 2 + i);
  const months = Array.from({ length: 12 }, (_, i) => i + 1);

  const totalAmount = students.reduce((sum, student) => {
    const payment = getPaymentForStudent(student.id);
    return sum + (payment?.amount ?? calculateTotal(student.id));
  }, 0);

  const paidAmount = payments
    .filter((p) => p.isPaid)
    .reduce((sum, p) => sum + p.amount, 0);

  const unpaidAmount = totalAmount - paidAmount;

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row gap-2 justify-end">
        <Button
          onClick={handleExportCSV}
          variant="outline"
          disabled={!team || payments.length === 0}
          data-testid="button-export-csv"
          className="w-full sm:w-auto"
        >
          <Download className="mr-2 h-4 w-4" />
          CSVダウンロード
        </Button>
        <Dialog open={showAutoGenerateDialog} onOpenChange={setShowAutoGenerateDialog}>
            <DialogTrigger asChild>
              <Button
                disabled={autoGenerateMutation.isPending || !team}
                data-testid="button-reset-unpaid"
                className="w-full sm:w-auto"
              >
                <RefreshCw className={`mr-2 h-4 w-4 ${autoGenerateMutation.isPending ? 'animate-spin' : ''}`} />
                月謝データ初期化
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>月謝データの初期化</DialogTitle>
                <DialogDescription>
                  {selectedYear}年{selectedMonth}月の未入金データをすべてリセットし、チーム情報の金額で初期化します。
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-4">
                <div className="bg-yellow-50 dark:bg-yellow-950/20 border border-yellow-200 dark:border-yellow-800 p-4 rounded-lg">
                  <p className="text-sm font-medium text-yellow-800 dark:text-yellow-200 mb-2">⚠️ 注意事項</p>
                  <ul className="text-sm text-yellow-700 dark:text-yellow-300 space-y-1">
                    <li>• 未入金（チェックなし）のデータのみがリセットされます</li>
                    <li>• 入金済み（チェック済み）のデータは変更されません</li>
                    <li>• チーム情報の金額設定が適用されます</li>
                  </ul>
                </div>
                <div className="bg-muted/50 p-4 rounded-lg space-y-2">
                  <p className="text-sm font-medium">適用される金額：</p>
                  <ul className="text-sm text-muted-foreground space-y-1">
                    <li>• チーム生の月謝：¥{(team?.monthlyFeeMember || 0).toLocaleString()}</li>
                    <li>• スクール生の月謝：¥{(team?.monthlyFeeSchool || 0).toLocaleString()}</li>
                    <li>• 年会費：{selectedMonth === (team?.annualFeeMonth || 4) ? `¥${(team?.annualFee || 0).toLocaleString()}` : '¥0'}</li>
                    <li>• 保険料：{selectedMonth === (team?.insuranceFeeMonth || 4) ? `¥${(team?.insuranceFee || 0).toLocaleString()}` : '¥0'}</li>
                    <li>• 入会金：¥0（手動設定が必要）</li>
                    <li>• 兄弟割引：該当者のみ ¥{(team?.siblingDiscount || 0).toLocaleString()}</li>
                  </ul>
                </div>
              </div>
              <div className="flex justify-end gap-2">
                <Button
                  variant="outline"
                  onClick={() => setShowAutoGenerateDialog(false)}
                  data-testid="button-cancel-reset"
                >
                  キャンセル
                </Button>
                <Button
                  onClick={() => {
                    autoGenerateMutation.mutate();
                    setShowAutoGenerateDialog(false);
                  }}
                  disabled={autoGenerateMutation.isPending}
                  data-testid="button-execute-reset"
                >
                  {autoGenerateMutation.isPending ? "実行中..." : "初期化する"}
                </Button>
              </div>
            </DialogContent>
        </Dialog>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">合計請求額</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">¥{totalAmount.toLocaleString()}</div>
            <p className="text-xs text-muted-foreground mt-1">
              {selectedYear}年{selectedMonth}月
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">入金済み</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">¥{paidAmount.toLocaleString()}</div>
            <p className="text-xs text-muted-foreground mt-1">
              {payments.filter(p => p.isPaid).length} / {students.length} 名
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">未収金</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-orange-600">¥{unpaidAmount.toLocaleString()}</div>
            <p className="text-xs text-muted-foreground mt-1">
              {payments.filter(p => !p.isPaid).length} 名未入金
            </p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>月謝一覧</CardTitle>
            <div className="flex gap-2">
              <Select value={String(selectedYear)} onValueChange={(v) => setSelectedYear(parseInt(v))}>
                <SelectTrigger className="w-[120px]" data-testid="select-year">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {years.map((year) => (
                    <SelectItem key={year} value={String(year)}>
                      {year}年
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>

              <Select value={String(selectedMonth)} onValueChange={(v) => setSelectedMonth(parseInt(v))}>
                <SelectTrigger className="w-[100px]" data-testid="select-month">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {months.map((month) => (
                    <SelectItem key={month} value={String(month)}>
                      {month}月
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <CardDescription>
            メンバーごとの月謝の詳細と支払い状況
          </CardDescription>
        </CardHeader>
        <CardContent>
          {students.length === 0 ? (
            <div className="text-center text-muted-foreground py-8">
              メンバーが登録されていません
            </div>
          ) : (
            <div className="space-y-3">
              {students.map((student) => {
                const payment = getPaymentForStudent(student.id);
                const baseAmount = payment?.baseAmount ?? getDefaultBaseAmount(student);
                const discount = payment?.discount ?? 0;
                const annualFee = payment?.annualFee ?? getDefaultAnnualFee();
                const entranceFee = payment?.entranceFee ?? getDefaultEntranceFee();
                const insuranceFee = payment?.insuranceFee ?? getDefaultInsuranceFee();
                const spotFee = payment?.spotFee ?? 0;
                const amount = payment?.amount ?? calculateTotal(student.id);

                return (
                  <div key={student.id} className="relative overflow-hidden rounded-xl border bg-gradient-to-br from-card to-card/50 p-4 shadow-sm hover-elevate transition-all">
                    <div className="flex items-start justify-between gap-4 mb-3">
                      {/* Left: Name, Category, and Sibling (horizontal layout) */}
                      <div className="flex-1">
                        <div className="text-xs font-medium text-muted-foreground mb-1.5">名前</div>
                        <div className="flex flex-wrap items-center gap-2">
                          <div className="text-lg font-semibold bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">{getFullName(student.lastName, student.firstName)}</div>
                          <Select
                            value={student.playerType || "unset"}
                            onValueChange={(value) => handleCategoryChange(student.id, value === "unset" ? null : value)}
                            data-testid={`select-category-${student.id}`}
                          >
                            <SelectTrigger className="w-[115px] h-8">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="unset">未設定</SelectItem>
                              <SelectItem value="team">チーム生</SelectItem>
                              <SelectItem value="school">スクール生</SelectItem>
                              <SelectItem value="inactive">休部</SelectItem>
                            </SelectContent>
                          </Select>
                          <div className="text-sm text-muted-foreground" data-testid={`text-sibling-discount-${student.id}`}>
                            {getSiblingDiscountStatus(student.id)}
                          </div>
                        </div>
                      </div>

                      {/* Right: Total and Status */}
                      <div className="text-right flex items-start gap-3">
                        <div className="bg-primary/5 rounded-lg px-4 py-2 border border-primary/10">
                          <div className="text-xs font-medium text-muted-foreground mb-0.5">合計金額</div>
                          <div className="text-2xl font-bold bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent" data-testid={`text-total-amount-${student.id}`}>
                            ¥{amount.toLocaleString()}
                          </div>
                        </div>
                        <label className="flex items-center gap-2 cursor-pointer group pt-2">
                          <Checkbox
                            checked={payment?.isPaid || false}
                            onCheckedChange={(checked) => handlePaidToggle(student.id, checked as boolean)}
                            data-testid={`checkbox-paid-${student.id}`}
                          />
                          <span className={`text-sm font-medium transition-colors ${payment?.isPaid ? 'text-green-600 dark:text-green-400' : 'text-orange-600 dark:text-orange-400'}`}>
                            {payment?.isPaid ? "入金済" : "未入金"}
                          </span>
                        </label>
                      </div>
                    </div>

                    {/* Bottom: Fee Details in Collapsible */}
                    <Collapsible defaultOpen={!payment?.isPaid} className="pt-4 border-t">
                      <CollapsibleTrigger className="flex items-center justify-between w-full text-sm font-medium text-muted-foreground hover:text-foreground transition-colors">
                        <span>明細</span>
                        <ChevronDown className="h-4 w-4 transition-transform duration-200 data-[state=open]:rotate-180" />
                      </CollapsibleTrigger>
                      <CollapsibleContent>
                        <div className="grid grid-cols-2 gap-3 pt-3">
                          <div className="space-y-1.5">
                            <label className="text-xs font-medium text-muted-foreground">月謝</label>
                            <div className="relative">
                              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground text-sm">¥</span>
                              <Input
                                type="number"
                                value={getEditingValue(student.id, 'baseAmount', baseAmount)}
                                onChange={(e) => setEditingValue(student.id, 'baseAmount', parseInt(e.target.value) || 0)}
                                onBlur={() => handleFieldUpdate(student.id, 'baseAmount')}
                                className="w-full text-right pl-8"
                                disabled={payment?.isPaid || false}
                                data-testid={`input-base-amount-${student.id}`}
                              />
                            </div>
                          </div>
                          <div className="space-y-1.5">
                            <label className="text-xs font-medium text-muted-foreground">割引</label>
                            <div className="relative">
                              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground text-sm">¥</span>
                              <Input
                                type="number"
                                value={getEditingValue(student.id, 'discount', discount)}
                                onChange={(e) => setEditingValue(student.id, 'discount', parseInt(e.target.value) || 0)}
                                onBlur={() => handleFieldUpdate(student.id, 'discount')}
                                className="w-full text-right pl-8"
                                disabled={payment?.isPaid || false}
                                data-testid={`input-discount-${student.id}`}
                              />
                            </div>
                          </div>
                          <div className="space-y-1.5">
                            <label className="text-xs font-medium text-muted-foreground">年会費</label>
                            <div className="relative">
                              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground text-sm">¥</span>
                              <Input
                                type="number"
                                value={getEditingValue(student.id, 'annualFee', annualFee)}
                                onChange={(e) => setEditingValue(student.id, 'annualFee', parseInt(e.target.value) || 0)}
                                onBlur={() => handleFieldUpdate(student.id, 'annualFee')}
                                className="w-full text-right pl-8"
                                disabled={payment?.isPaid || false}
                                data-testid={`input-annual-fee-${student.id}`}
                              />
                            </div>
                          </div>
                          <div className="space-y-1.5">
                            <label className="text-xs font-medium text-muted-foreground">入会金</label>
                            <div className="relative">
                              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground text-sm">¥</span>
                              <Input
                                type="number"
                                value={getEditingValue(student.id, 'entranceFee', entranceFee)}
                                onChange={(e) => setEditingValue(student.id, 'entranceFee', parseInt(e.target.value) || 0)}
                                onBlur={() => handleFieldUpdate(student.id, 'entranceFee')}
                                className="w-full text-right pl-8"
                                disabled={payment?.isPaid || false}
                                data-testid={`input-entrance-fee-${student.id}`}
                              />
                            </div>
                          </div>
                          <div className="space-y-1.5">
                            <label className="text-xs font-medium text-muted-foreground">保険料</label>
                            <div className="relative">
                              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground text-sm">¥</span>
                              <Input
                                type="number"
                                value={getEditingValue(student.id, 'insuranceFee', insuranceFee)}
                                onChange={(e) => setEditingValue(student.id, 'insuranceFee', parseInt(e.target.value) || 0)}
                                onBlur={() => handleFieldUpdate(student.id, 'insuranceFee')}
                                className="w-full text-right pl-8"
                                disabled={payment?.isPaid || false}
                                data-testid={`input-insurance-fee-${student.id}`}
                              />
                            </div>
                          </div>
                          <div className="space-y-1.5">
                            <label className="text-xs font-medium text-muted-foreground">スポット</label>
                            <div className="relative">
                              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground text-sm">¥</span>
                              <Input
                                type="number"
                                value={getEditingValue(student.id, 'spotFee', spotFee)}
                                onChange={(e) => setEditingValue(student.id, 'spotFee', parseInt(e.target.value) || 0)}
                                onBlur={() => handleFieldUpdate(student.id, 'spotFee')}
                                className="w-full text-right pl-8"
                                disabled={payment?.isPaid || false}
                                data-testid={`input-spot-fee-${student.id}`}
                              />
                            </div>
                          </div>
                        </div>
                      </CollapsibleContent>
                    </Collapsible>
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
